#!/usr/bin/env python3
"""Deterministic reviewed-contract bundle merge.

`cand check --contracts` accepts exactly ONE contract file (a repeated flag
is last-wins; see the CVE-replay harness history), so the reviewed bundles
are merged offline into a single file. This tool is the only supported way
to produce that file:

  - the bundle list is explicit and ordered (default: contracts/libc.yaml
    plus every contracts/bundles/*.yaml in sorted order);
  - duplicate symbols across bundles are REJECTED (exit 1, no last-wins);
  - malformed bundles (missing schema/name/version/symbols, wrong schema
    id, stray keys) are REJECTED;
  - output is byte-identical for identical inputs (stable order, stable
    comments);
  - with --digests, the SHA-256 of every input bundle and of the merged
    file is printed for evidence records.

The merged file is a build product and must not be committed.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys

EXPECTED_SCHEMA = "cand.api-contract/v1"


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def load_bundle(path: str) -> dict:
    """Parse a bundle into header lines and symbol-entry blocks."""
    lines = open(path).read().splitlines()
    header = {}
    symbols_start = None
    for i, line in enumerate(lines):
        if line.startswith("symbols:"):
            symbols_start = i
            break
        m = re.match(r"^(schema|name|version):\s*(.+)$", line)
        if m:
            header[m.group(1)] = m.group(2).strip().strip('"')
    if symbols_start is None:
        raise SystemExit(f"{path}: no 'symbols:' section")
    for key in ("schema", "name", "version"):
        if key not in header:
            raise SystemExit(f"{path}: missing '{key}:' header")
    if header["schema"] != EXPECTED_SCHEMA:
        raise SystemExit(f"{path}: unexpected schema {header['schema']!r}")

    entries = []
    current = None
    for line in lines[symbols_start + 1:]:
        if not line.strip() or line.strip().startswith("#"):
            continue
        m = re.match(r"^  - symbol:\s*(\S+)\s*$", line)
        if m:
            if current is not None:
                entries.append(current)
            current = {"symbol": m.group(1), "lines": [line]}
            continue
        if current is None:
            raise SystemExit(f"{path}: content before first symbol entry: {line!r}")
        if not line.startswith((" ", "-")) and line.strip():
            raise SystemExit(f"{path}: unexpected top-level line: {line!r}")
        current["lines"].append(line)
    if current is not None:
        entries.append(current)
    if not entries:
        raise SystemExit(f"{path}: no symbol entries")
    return {"path": path, "header": header, "entries": entries}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="merged contract file to write")
    ap.add_argument("--bundle", action="append", default=[],
                    help="bundle file (repeatable); default = libc.yaml + bundles/*.yaml sorted")
    ap.add_argument("--digests", action="store_true",
                    help="print input and output SHA-256 digests")
    args = ap.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    bundles = list(args.bundle)
    if not bundles:
        bundles = [os.path.join(root, "contracts", "libc.yaml")]
        bundle_dir = os.path.join(root, "contracts", "bundles")
        bundles += sorted(
            os.path.join(bundle_dir, f)
            for f in os.listdir(bundle_dir) if f.endswith(".yaml")
        )

    loaded = [load_bundle(p) for p in bundles]

    seen = {}
    for bundle in loaded:
        for entry in bundle["entries"]:
            name = entry["symbol"]
            if name in seen:
                print(f"merge error: duplicate symbol {name!r} in "
                      f"{bundle['path']} (already defined by {seen[name]})",
                      file=sys.stderr)
                return 1
            seen[name] = bundle["path"]

    base = loaded[0]
    out = []
    out.append(f"schema: {EXPECTED_SCHEMA}")
    out.append(f"name: {base['header']['name']}")
    out.append(f"version: {base['header']['version']}")
    out.append("")
    out.append("# Reviewed merged contract set (BUILD PRODUCT; do not commit).")
    out.append("# Generated by scripts/contracts/merge_contracts.py from:")
    for bundle in loaded:
        out.append(f"#   {os.path.relpath(bundle['path'], root)} "
                   f"[{bundle['header']['name']} {bundle['header']['version']}]")
    out.append("#")
    out.append("# Duplicate symbols across bundles are rejected at merge time;")
    out.append("# there is no last-wins behavior. See "
               "docs/contracts/EXTERNAL-API-TRUST-MODEL.md.")
    out.append("")
    out.append("symbols:")
    for bundle in loaded:
        out.append(f"  # ---- {os.path.relpath(bundle['path'], root)} "
                   f"({bundle['header']['name']}) ----")
        for entry in bundle["entries"]:
            out.extend(entry["lines"])

    text = "\n".join(out) + "\n"
    with open(args.out, "w") as f:
        f.write(text)

    if args.digests:
        for bundle in loaded:
            print(f"bundle {os.path.relpath(bundle['path'], root)} "
                  f"{sha256_file(bundle['path'])}")
        print(f"merged {os.path.relpath(os.path.abspath(args.out), root)} "
              f"{sha256_file(args.out)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
